# Name of executable file
PROJECT_NAME = bank.exe

# All source files
 
SRC = src/menu.c\
src/edit.c\
src/erase.c\
src/close.c\
src/new_acc.c\
src/see.c\
src/transact.c\
src/view_list.c\
src/interest.c\
bank.c\

#Including all source files

INC = -Iinc\

$(PROJECT_NAME): $(SRC)
	gcc $(INC) $(SRC)  -o bank.exe

#run command to run the executable file

run: $(PROJECT_NAME)
	$(PROJECT_NAME)









